package com.timetablegenerator.delta;

public enum PropertyType {

    TERM, CAMPUS, ROOM, NAME, SERIAL_NUMBER,
    SECTION_TYPE, SECTION, REPEATING_PERIOD, ONE_TIME_PERIOD,
    TIMETABLE, COURSE, CROSS_LISTING, PRE_REQUISITE,
    ANTI_REQUISITE, CO_REQUESITE, DESCRIPTION, NOTE, WAITING_LIST,
    NUM_WAITING, MAX_WAITING, IS_FULL, NUM_ENROLLED,
    MAX_ENROLLED, IS_CANCELLED, IS_ONLINE, IS_ALTERNATING,
    SUPERVISOR;

    public String getFieldName(){
        return this.name();
    }
}