package com.timetablegenerator.delta;

public enum PropertyType {

    TERM, CAMPUS, ROOM, NAME, SERIAL,
    SECTION_TYPE, SECTION, REPEATING_PERIOD, SINGLE_PERIOD,
    TIMETABLE, COURSE, CROSSLISTING, PREREQUISITE,
    ANTIREQUISITE, DESCRIPTION, NOTE, WAITING_LIST,
    NUM_WAITING, MAX_WAITING, IS_FULL, NUM_ENROLLED,
    MAX_ENROLLED, IS_CANCELLED, IS_ONLINE, IS_ALTERNATING,
    SUPERVISOR
}