FROM jenkins/jenkins:alpine
ENV EDITED_ON 2018-08-29
COPY plugins.txt /
COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy
RUN /usr/local/bin/install-plugins.sh < /plugins.txt
USER root
RUN apk update && apk add docker
USER jenkins

