FROM ownaginatious/armv6h-archlinux-java-oracle:latest
ENV EDITED_ON 2016-07-11 \
    KEYSTORE=$JAVA_HOME/jre/lib/security/cacerts

RUN pacman -Sy --noconfirm --noprogressbar curl wget git docker openssh && \
    wget https://letsencrypt.org/certs/isrgrootx1.pem && \
    wget https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.der && \
    wget https://letsencrypt.org/certs/lets-encrypt-x4-cross-signed.der && \
    keytool -trustcacerts -keystore $KEYSTORE -storepass changeit -noprompt -importcert -alias isrgrootx1 -file isrgrootx1.pem && \
    keytool -trustcacerts -keystore $KEYSTORE -storepass changeit -noprompt -importcert -alias letsencryptauthorityx3 -file lets-encrypt-x3-cross-signed.der && \
    keytool -trustcacerts -keystore $KEYSTORE -storepass changeit -noprompt -importcert -alias letsencryptauthorityx4 -file lets-encrypt-x4-cross-signed.der
 
CMD [ -d '/ssh_keys' ] && (cp -R /ssh_keys /root/.ssh/ && \
                           chown -R root:root /root/.ssh/ && \
                           chmod 400 -R /root/.ssh/) || true && \
    wget "http://jenkins.timetablegenerator.io/jnlpJars/slave.jar" && \
    java -jar "./slave.jar" \
         -jnlpUrl "https://jenkins.timetablegenerator.io/computer/${JENKINS_SLAVE_ID}/slave-agent.jnlp" \
         -secret "${JENKINS_SLAVE_SECRET}"

