FROM ownaginatious/armv6h-archlinux-java:latest
ENV EDITED_ON 2016-07-06
RUN pacman -Sy --noconfirm curl wget git docker openssh

CMD [ -d '/ssh_keys' ] && (cp -R /ssh_keys /root/.ssh/ && \
                           chown -R root:root /root/.ssh/ && \
                           chmod 400 -R /root/.ssh/) || true && \
    wget "http://jenkins.timetablegenerator.io/jnlpJars/slave.jar" && \
    java -jar "./slave.jar" \
         -jnlpUrl "https://jenkins.timetablegenerator.io/computer/${JENKINS_SLAVE_ID}/slave-agent.jnlp" \
         -secret "${JENKINS_SLAVE_SECRET}"

